version: "3.7"

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  web:
    build: .
    restart: unless-stopped
    container_name: domi.web
    ports:
      - "8018:8000"
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/
    depends_on:
      - db
  db:
    image: postgres:17
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: domi.postgres
    restart: unless-stopped
    environment:
      # Sets up the Postgres DB with the below credentials
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres

