# Generated by Django 4.1.3 on 2022-11-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('departamento', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['departamento', 'name'],
                'unique_together': {('name', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zona', models.CharField(max_length=20)),
                ('cod_zona', models.IntegerField()),
                ('status', models.IntegerField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipio')),
            ],
            options={
                'ordering': ['cod_zona', 'name'],
                'unique_together': {('municipio', 'name', 'zona', 'cod_zona')},
            },
        ),
    ]
