# Generated by Django 4.1.3 on 2022-12-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('numero_radicado', models.CharField(max_length=24, unique=True)),
                ('cel_uno', models.CharField(blank=True, max_length=16, null=True)),
                ('cel_dos', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=150)),
                ('ip', models.GenericIPAddressField()),
                ('paciente_nombre', models.CharField(max_length=150)),
                ('paciente_cc', models.CharField(max_length=12)),
                ('paciente_data', models.JSONField()),
                ('domiciliario_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('domiciliario_ide', models.CharField(blank=True, max_length=25, null=True)),
                ('domiciliario_empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=64, null=True)),
                ('alistamiento', models.DateTimeField(blank=True, null=True)),
                ('alistado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('despachado', models.DateTimeField(blank=True, null=True)),
                ('acta_entrega', models.CharField(blank=True, max_length=150, null=True)),
                ('factura', models.CharField(blank=True, max_length=150, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.barrio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipio')),
            ],
        ),
    ]
