# Generated by Django 4.1.3 on 2023-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_radicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacion',
            name='creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='created'),
        ),
    ]
