# Generated by Django 4.1.3 on 2023-05-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_radicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med_Controlado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cum', models.CharField(max_length=24)),
                ('nombre', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('field_one', models.CharField(blank=True, max_length=24, null=True)),
                ('field_two', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
    ]
