# Generated by Django 4.1.3 on 2023-05-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_med_controlado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='med_controlado',
            options={'verbose_name': 'medicamento controlado', 'verbose_name_plural': 'Medicamentos Controlados'},
        ),
    ]
