# Generated by Django 4.1.3 on 2023-09-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cod_dane',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp', models.CharField(max_length=24)),
                ('bod', models.CharField(max_length=24)),
                ('drogueria', models.CharField(max_length=128)),
                ('correo_coordinador', models.CharField(blank=True, max_length=128, null=True)),
                ('dia_ped', models.CharField(blank=True, max_length=24, null=True)),
                ('estado', models.CharField(blank=True, max_length=24, null=True)),
                ('modalidad', models.CharField(max_length=24)),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=24)),
                ('correo_disp', models.CharField(blank=True, max_length=128, null=True)),
                ('responsable', models.CharField(blank=True, max_length=128, null=True)),
                ('cedula', models.CharField(blank=True, max_length=64, null=True)),
                ('celular', models.CharField(blank=True, max_length=64, null=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('medicar', models.CharField(blank=True, max_length=8, null=True)),
                ('tent', models.IntegerField()),
                ('analista', models.CharField(blank=True, max_length=128, null=True)),
                ('ult_fecha_disp', models.DateTimeField(blank=True, null=True)),
                ('aux_pqr', models.CharField(blank=True, max_length=128, null=True)),
                ('transp_1', models.CharField(blank=True, max_length=128, null=True)),
                ('transp_2', models.CharField(blank=True, max_length=128, null=True)),
                ('correo_contacto_eps', models.CharField(blank=True, max_length=128, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipio')),
            ],
            options={
                'db_table': 'base_centros',
            },
        ),
    ]
