# Generated by Django 4.1.3 on 2024-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_municipio_activo_municipio_cod_dane_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacion',
            name='convenio',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
