# Generated by Django 4.1.3 on 2024-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_radicacion_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacion',
            name='convenio',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
