# Generated by Django 4.1.3 on 2025-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_radicacion_visto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapMutualSer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duracion', models.FloatField(null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('texto_error', models.TextField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'base_scrapper',
            },
        ),
    ]
