# Generated by Django 4.1.3 on 2025-09-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_scrapmutualser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutualser',
            fields=[
                ('documento', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(db_index=True, max_length=10)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_beneficiario', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_ips', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mutualser',
                'managed': False,
            },
        ),
    ]
