# Generated by Django 4.1.3 on 2025-09-01 16:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_mutualser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelularesRestringidos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numero', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(3000000000), django.core.validators.MaxValueValidator(3259999999)])),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_celulares_restringidos',
            },
        ),
    ]
