# Generated by Django 4.1.3 on 2025-09-05 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_celularesrestringidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numero', models.BigIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(3000000000), django.core.validators.MaxValueValidator(3259999999)])),
                ('otp_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='radicacion',
            name='cel_uno_validado',
            field=models.BooleanField(default=False),
        ),
    ]
