# Generated by Django 4.1.3 on 2025-10-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_otpsms_radicacion_cel_uno_validado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosRestringidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_usuarios_restringidos',
            },
        ),
        migrations.AddConstraint(
            model_name='usuariosrestringidos',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'documento'), name='unique_tipo_documento_documento'),
        ),
    ]
