# Generated by Django 4.1.3 on 2026-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_usuariosrestringidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacion',
            name='fecha_anulacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='motivo',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='usuario_anula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
