# Generated by Django 4.1.3 on 2026-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_usuariosrestringidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foneca',
            fields=[
                ('documento', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(db_index=True, max_length=10)),
                ('primer_apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grupo_etareo', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=128, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contratante', models.CharField(blank=True, max_length=50, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('gerencia_territorial', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'foneca',
            },
        ),
        migrations.AddIndex(
            model_name='foneca',
            index=models.Index(fields=['documento', 'tipo_documento'], name='idx_foneca_doc_tipo'),
        ),
        migrations.AddIndex(
            model_name='foneca',
            index=models.Index(fields=['estado'], name='idx_foneca_estado'),
        ),
        migrations.AddIndex(
            model_name='foneca',
            index=models.Index(fields=['municipio'], name='idx_foneca_municipio'),
        ),
        migrations.AddIndex(
            model_name='foneca',
            index=models.Index(fields=['eps'], name='idx_foneca_eps'),
        ),
        migrations.AlterUniqueTogether(
            name='foneca',
            unique_together={('documento', 'tipo_documento')},
        ),
    ]
