# Generated by Django 4.1.3 on 2026-04-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_foneca_foneca_idx_foneca_doc_tipo_and_more'),
        ('base', '0015_radicacion_fecha_anulacion_radicacion_motivo_and_more'),
    ]

    operations = [
    ]
