# Generated by Django 4.1.3 on 2026-05-06 08:33

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_20260430_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionOCRTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completado', 'completado'), ('fallido', 'fallido'), ('advertencia', 'advertencia'), ('en ejecucion', 'en ejecucion'), ('pendiente', 'pendiente')], max_length=24)),
                ('provider', models.CharField(default='anthropic', max_length=32)),
                ('model_id', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_read_input_tokens', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_usage', models.JSONField(blank=True, null=True)),
                ('drive_file_id', models.CharField(db_index=True, max_length=128)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('discard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SAPArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='Original id__ from source', unique=True)),
                ('barra', models.CharField(db_index=True, max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('grupo_articulo', models.CharField(max_length=100)),
                ('molecula_id', models.CharField(max_length=20)),
                ('nombre_molecula', models.CharField(max_length=255)),
                ('atc', models.CharField(blank=True, max_length=20, null=True)),
                ('ean14', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_inventario', models.CharField(blank=True, max_length=20, null=True)),
                ('unidad_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_unidad_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_ean14', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_ean14', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_compra_ean14', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unidad_venta', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_unidad_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=50, null=True)),
                ('cum', models.CharField(blank=True, max_length=50, null=True)),
                ('invima', models.CharField(blank=True, max_length=100, null=True)),
                ('regulado', models.CharField(default='N', max_length=1)),
                ('valor_regulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('controlado', models.CharField(default='N', max_length=1)),
                ('refrigerado', models.CharField(default='N', max_length=1)),
                ('iva_ventas', models.CharField(blank=True, max_length=20, null=True)),
                ('iva_compras', models.CharField(blank=True, max_length=20, null=True)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField()),
                ('usuario', models.CharField(max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('bodega_defecto', models.CharField(blank=True, max_length=20, null=True)),
                ('inactivo', models.CharField(default='N', max_length=1)),
                ('bodega_bloqueada', models.CharField(default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Articulo SAP',
                'verbose_name_plural': 'Articulos SAP',
                'db_table': 'sap_articulos',
            },
        ),
        migrations.CreateModel(
            name='SearchBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('completado', 'completado'), ('fallido', 'fallido'), ('advertencia', 'advertencia'), ('en ejecucion', 'en ejecucion'), ('pendiente', 'pendiente')], max_length=24)),
                ('provider', models.CharField(default='anthropic', max_length=32)),
                ('model_id', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_read_input_tokens', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_usage', models.JSONField(blank=True, null=True)),
                ('article_numero', models.IntegerField()),
                ('article_nombre', models.CharField(max_length=512)),
                ('ips', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.AlterModelOptions(
            name='radicacion',
            options={'ordering': ['-datetime', '-id']},
        ),
        migrations.AddIndex(
            model_name='radicacion',
            index=models.Index(fields=['-datetime', '-id'], name='base_radica_datetim_bca38b_idx'),
        ),
        migrations.AddField(
            model_name='searchbarra',
            name='article_sap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_sap', to='base.saparticle'),
        ),
        migrations.AddField(
            model_name='searchbarra',
            name='prescription_ocr_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barra_transactions', to='base.prescriptionocrtransaction'),
        ),
        migrations.AddField(
            model_name='prescriptionocrtransaction',
            name='radicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_ocr_transactions', to='base.radicacion'),
        ),
        migrations.AddIndex(
            model_name='searchbarra',
            index=models.Index(fields=['prescription_ocr_transaction', 'status'], name='base_search_prescri_64e70d_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchbarra',
            constraint=models.UniqueConstraint(fields=('prescription_ocr_transaction', 'article_numero'), name='uniq_prescription_barra_txn_article_numero'),
        ),
        migrations.AddIndex(
            model_name='prescriptionocrtransaction',
            index=models.Index(fields=['drive_file_id', 'created_at'], name='base_prescr_drive_f_60ed52_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionocrtransaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['result'], name='result_gin_idx'),
        ),
    ]
