# Generated by Django 4.1.3 on 2023-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasProcesadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('factura', models.CharField(max_length=24, unique=True)),
                ('fecha_factura', models.DateTimeField()),
                ('acta', models.CharField(max_length=24)),
                ('numero_autorizacion', models.CharField(max_length=24, unique=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
                ('link_soporte', models.CharField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, max_length=128, null=True)),
                ('resp_cajacopi', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturas_procesadas',
            },
        ),
    ]
