name: Python application

on: [pull_request_target]
env: # Or as an environment variable
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
      EMAIL_BCC: ${{ secrets.EMAIL_BCC }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      EMAIL_API_MEDICAR: ${{ secrets.EMAIL_API_MEDICAR }}
      PWD_API_MEDICAR: ${{ secrets.PWD_API_MEDICAR }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Django commands
      run: |
        python manage.py collectstatic
    - name: Unitests
      run: |
        python manage.py test core.apps.base.tests.test_wizards
        python manage.py test core.apps.base.tests.test_autorizacionServicio
        python manage.py test core.apps.base.tests.test_fotoFormulaMedica
        python manage.py test core.apps.base.tests.test_eligeMunicipio
        python manage.py test core.apps.base.tests.test_digitaDireccionBarrio
        python manage.py test core.apps.base.tests.test_digitaCelular
        python manage.py test core.apps.base.tests.test_digitaCorreo
